[pytest]
testpaths = tests

markers =
    smoke: lightweight smoke tests
    performance: tests related to performance
    component: tests of isolated components
    unit: functional tests of subsystems
    integration: tests of integration between some components